### ISSUE TITLE
synchronizeClient process hangs if only one of the clients has failure

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#16] opened 2016-04-21 19:50 UTC
this issue can be easily reproduced in multiple client tests after adding any assertion error in one of the clients.

**Comment by jd0-sag** [comment] 2016-04-21 20:02
It probably isn't hanging in synchronizeClient (that call doesn't really do much but it is probably the last thing the harness did before the hang).

I suspect that the problem here is with how we are waiting for the clients:  1 thread starts all the client processes and then waits for all of them.  The problem is that the wait is done on the list of processes.  If a later process crashed and an earlier one was waiting on it to do something before exiting, then we get stuck.

The solution will be to change the way clients are started and waited for to more closely resemble what is done for servers (since they are treated independently).

The question remains of what to do with the thread which normally starts them.  For now, the easiest answer is probably to leave it waiting for them all, even if that is redundant, since it will still give the correct behavior.  Another option would be to use it to wait on some kind of timeout threshold to detect a hung test.

**Comment by jd0-sag** [comment] 2016-05-06 22:02
I have a solution to this, which I am just cleaning up.

I added some integration tests which demonstrate the problem and are resolved by the fix, as well.

In essence, I inverted the relationship between InterruptableClientManager and ClientRunner so that the client manager doesn't need to wait for each specific ClientRunner, in order.  Instead, the ClientRunners now notify it when they terminate so it only needs to keep count of how many are outstanding and immediately terminate all of them and fail out, the moment one client returns non-zero error code.

In the future, this same waiting point could be used for some kind of timeout mechanism.

**Closed** 2016-05-09 23:17 UTC
Labels: bug, in progress
